on:
  [push, pull_request]
jobs:
    evaluator:
     name: Evaluator Job
     runs-on: ubuntu-18.04
     env:
       JWT_SECRET: sonhograndementeabertaespiritoempreendedor
     steps: 
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v3
         with:
            node-version: '16'
       - run: npm install
         name: Install Dependencies
       - run: npm test
         name: Run Tests
         